spring:
 profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: application-dev
server:
  port: 8888
---
spring:
  profiles: test
  application:
    name: application-test
server:
  port: 9999