server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.246.54/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: 118756
  jpa:
    show-sql: true
    database: mysql
logging:
  level:
    com.tensquare.base.*: debug